### ISSUE TITLE
Unused attribute n_domain in VAE

### ISSUE THREAD

**Issue by parashardhapola** [jsxlei/SCALEX#10]
Wondering what the role of `n_domain` attribute here is:
https://github.com/jsxlei/SCALEX/blob/531e3755da962853ecd2a622379addd37b290e3f/scalex/net/vae.py#L42

Does not seem to be consumed by the class internally.

**Comment by jsxlei** [comment]
The self.n_domain is just to keep the information of how many domains (batches of single-cell datasets). It is not used internally and  only serves as a api for outside usage for further testing.

**Comment by parashardhapola** [comment]
Thanks for the prompt response. It's okay to close this. :)
