### ISSUE TITLE
TypeError: SCALEX() got an unexpected keyword argument 'test_list

### ISSUE THREAD

**Issue by houruiyan** [jsxlei/SCALEX#11]
Hello , thank you very much for this useful tool. 
I meet this error. When I reinstall SCALEX by using 
`pip install git+https://github.com/jsxlei/scalex.git
`
```
File "/home/houruiyan/.conda/envs/specifiVelocyto/bin/SCALEX.py", line 82, in <module>
    show=False,
TypeError: SCALEX() got an unexpected keyword argument 'test_list'
```

Around 20 days ago, it can work. 
I use this command.

`nohup SCALEX.py --data_list final_cave.h5ad final_surface.h5ad final_zebrafish.h5ad   --batch_categories cave surface zebrafish  --outdir ./SCALEX_out/ &`

Hope to get your help! Thank you!

**Comment by jsxlei** [comment]
I have fix this error. You can reinstall it by pip install git+https://github.com/jsxlei/scalex.git. Then it will work. Thanks!

**Comment by houruiyan** [comment]
ok ,thank you! It works~

**Comment by houruiyan** [comment]
I close this question.
