### ISSUE TITLE
Paths are incorrectly handled

### ISSUE THREAD

**Issue by scottgigante-immunai** [jsxlei/SCALEX#14]
[Concatenating paths as strings](https://github.com/jsxlei/SCALEX/blob/main/scalex/function.py#L127) is not recommended (and will cause errors e.g. in windows). Recommend either [pathlib](https://docs.python.org/3/library/pathlib.html) or at a bare minimum [os.path](https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module).

**Comment by jsxlei** [comment]
Thank you for your suggestions. We would like to replace them with os.path and the new version will be soon updated. We will also test pathlib at the same time.
