### ISSUE TITLE
SCALEX metrics help

### ISSUE THREAD

**Issue by kostaslazaros** [jsxlei/SCALEX#16]
Hello there,

I've run the SCALEX  pancreas data integration example on my pc.

I would like to use one of SCALEX's metrics; more specifically:  batch_entropy_mixing_score.

I've tried to run it like this; batch_entropy_mixing_score(adata_ref, 'batch').

After a while I get this error message; ValueError: Found array with dim 32. expected <= 2.

Any ideas on how to fix this issue?

**Comment by jsxlei** [comment]
Hi, the batch_entropy_mixing_score takes two inputs: one is an array of cell representation (not anndata object, use adata.X or adata.obm['latent'] instead) and the other is the batch id array (use adata.obs['batch']).
Please let me know if any question you have.

**Comment by kostaslazaros** [comment]
Hello there again!!!

Many thanks for answering!!!

I followed the instructions you gave me!!! It did work on the adata_raw version of the pancreas dataset (pre batch-effect correction).

I tried doing the same thing for the adata_ref version of the pancreas dataset  (post batch-effect correction). However, on the adata_ref version I get the following error;

"sparse matrix length is ambiguous; use getnnz() or shape[0]"

Any tips for that one?

Again, thank you very much for responding!!

**Comment by jsxlei** [comment]
In this case, you can transform the csr_matrix (sparse matrix) into dense matrix by adata.X.toarray().

We usually use the 'X_umap' coordinate to calculate the entropy_mixing_score. That means you can use adata.obsm['X_umap'] instead of adata.X.

Let me know if you still have any other questions.

**Comment by kostaslazaros** [comment]
Okay, got it! I'm guessing X_umap refers to the data's umap embeddings ? Is this done so that we can have a common comparison space (i.e: 2 arrays that have the same shape)? 

Is the above input also, what should be used for the calculation of silhouette score? The reason why I ask is because I ran silhouette_score for both the adata_raw and adata_ref by using the X_umap coordinate and i got the following result;

silhouette_score(adata_raw) -> 0.03117 

silhouette_score(adata_ref) -> -0.1458

**Comment by jsxlei** [comment]
You shouldn't do the calculation using the raw data which is adata.X, instead using adata.obsm['X_umap'] or adata.obsm['latent'], the former is the umap embedding output by SCALEX, the latter is the latent embedding obtained by SCALEX, while adata.X is the input of SCALEX not the results.

**Comment by kostaslazaros** [comment]
For calculating silhouette_score I used adata_raw.obsm['X_umap'] and adata_ref.obsm['X_umap'].

The silhouette_score for adata_raw.absm['X_umap'] had a value of 0.03117.
Thing is the silhouette_score for adata_ref.obsm['X_umap'] had a value of -0.1458.

My confusion stems from the fact that negative silhouette scores are not desirable.

Sorry for for the confusion on my question above.

**Comment by jsxlei** [comment]
Does the umap looks good? It is not supposed to be a negative value. Just make sure what your input to silhouettte_score, they should be adata.obsm['X_umap'] and adata.obs['cell_type'] (which is the ground truth cell annotations instead adata.obs['batch']).

Please let me know if anything wrong.

**Comment by kostaslazaros** [comment]
You are right!!! That did fix it!!!!

Many thanks for the replies and your patience!!!
