### ISSUE TITLE
can not repeat your tutorial "ntegrating scATAC-seq data using SCALEX"

### ISSUE THREAD

**Issue by daweibushen** [jsxlei/SCALEX#17]
just as follow file, could you fix it?
[Uploading Integrating scATAC-seq data using SCALEX.zip…]()

**Comment by jsxlei** [comment]
Hi thank you for your interests. Could you provide more details to help fix your issue including the data you use, the SCALEX version, the command and the error or results?

**Comment by daweibushen** [comment]
[Integrating scATAC-seq data using SCALEX.zip](https://github.com/jsxlei/SCALEX/files/10810795/Integrating.scATAC-seq.data.using.SCALEX.zip)

**Comment by jsxlei** [comment]
You can install the newest version by pip install git+https://github.com/jsxlei/scalex.git or pip install scalex==0.2.0 (the version used in the tutorial) to reproduce the results in the tutorial. Let me know if this solves your issue.
