### ISSUE TITLE
mouse_brain_atac datasets failed to download

### ISSUE THREAD

**Issue by blastlove** [jsxlei/SCALEX#25]
When I run the tutorial, the url http://zhanglab.net/scalex-tutorial/mouse_brain_atac.h5ad is unavailable. Could you please provide an alternative link? Thanks a lot!

**Comment by jsxlei** [comment]
Sorry for the inconvenience. Here is an alternative link to download it https://www.dropbox.com/scl/fi/affgmiktg49s3ogmzq8ss/mouse_brain_atac.h5ad?rlkey=iejewl06wuvnflyqfj2rgabwi&dl=0 . 
Let me know if there is any problem for this.
