### ISSUE TITLE
Preprocessing of ATAC Data

### ISSUE THREAD

**Issue by blastlove** [jsxlei/SCALEX#26]
I installed the 1.0.2 Version of SCALEX from PyPI and integrated **mouse_brain_atac data** according to the SCALEX tutorial. I found that there's no "**Normalizing total per cell**" procedure when preprocessing the ATAC data. It seems like that the developer commented the relative code.
<img width="309" alt="屏幕截图 2023-11-10 121123" src="https://github.com/jsxlei/SCALEX/assets/111514867/1cbf7f01-07e7-4aa2-be0f-ac16b55a0eca">

The final integration result I got looked very strange.
<img width="816" alt="image" src="https://github.com/jsxlei/SCALEX/assets/111514867/08ef73cf-e8df-43a0-a61b-9842dbaf919e">

Then I uncommented the above code and below is the full preprocessing procedure of ATAC data.
<img width="599" alt="image" src="https://github.com/jsxlei/SCALEX/assets/111514867/2dad0bde-3d64-4b7b-aeed-02d59cfd8c69">

This time I got a pretty good result.
<img width="817" alt="屏幕截图 2023-11-10 121352" src="https://github.com/jsxlei/SCALEX/assets/111514867/271c5c54-0b5e-4a14-a606-14e40ee1df7e">

So I'm really confused as to why the developer deleted the "Normalizing total per cell" procedure in the ATAC data preprocessing. Since each number in adata.X is either 0 or 1, **the batch scale which employs the MaxAbsScaler will be meaningless** if the previous normalizaion precedure is canceled.

Really appreciate it if you can help with this!

**Comment by jsxlei** [comment]
Thank you for your interest in SCALEX. Normalize total combine with batch scale can do somewhat smoothing numerical values gap between different batches. In later cases, we found that even without normalize total, not testing on the example case, it can also perform very well, so we just remove the normalize total processing. You are right, if without normalize total, batch scale is not neccessary. To make this more stable, we are considering add it back.
