### ISSUE TITLE
CITE-seq

### ISSUE THREAD

**Issue by ebrombacher** [jsxlei/SCALEX#3]
Hi,
As in your preprint you showed that SCALEX can also be applied to CITE-seq data, I was wondering if you could provide an example code snippet of how this can be done.
Many thanks!

**Comment by ericli0419** [comment]
Hi, the demo code is presented below. Also, I recommend that you install a development version of SCALEX from https://github.com/ericli0419/SCALEX. 
```
# RNA adata preprocess
sc.pp.normalize_per_cell(rna_data, counts_per_cell_after=1e4)
sc.pp.log1p(rna_data)
sc.pp.highly_variable_genes(rna_data, n_top_genes=1890, batch_key='batch', inplace=False, subset=True)

# Protein adata preprocess
sc.pp.normalize_per_cell(protein_data, counts_per_cell_after=1e4)
sc.pp.log1p(protein_data)

# Concatenate RNA and protein adata
norm_full_data = anndata.AnnData(
    X=np.concatenate(
        [
            rna_data.X,
            protein_data.X,
        ],
        axis=1,
    )
)

col_names = np.concatenate([rna_data.var_names, protein_data.var_names])
norm_full_data.var_names = col_names
norm_full_data.write('spleen_CITE.h5ad')

# SCALEX Integration
adata_scalex=SCALEX('spleen_CITE.h5ad',batch_name='batch',min_features=1, min_cells=1, outdir='spleen_log_output/',show=False,gpu=9,batch_size=64,processed=True)
```

**Comment by ebrombacher** [comment]
@ericli0419 Great! Thanks so much for your prompt and helpful reply!

**Comment by ericli0419** [comment]
> 
A short answer is YES. For CITE-seq data, the protein and RNA data from one cell are labeled with the same batch.

**Comment by ericli0419** [comment]
> @ericli0419 Great! Thanks so much for your prompt and helpful reply! One quick follow-up question: Do I understand it correctly that the RNA and protein data are combined into one single batch?

A short answer is YES. For CITE-seq data, the protein and RNA data from one cell are labeled with the same batch.

**Comment by ebrombacher** [comment]
Ok, I see, thank you!
