### ISSUE TITLE
`outdir=None` throws errors

### ISSUE THREAD

**Issue by scottgigante-immunai** [jsxlei/SCALEX#8]
https://github.com/jsxlei/SCALEX/blob/main/scalex/function.py#L232 implies that outdir can be set to None to turn off writing results to disk. However, this leads to errors elsewhere in the code, e.g. 

```
Traceback (most recent call last):
    adata = scalex.SCALEX(
  File "/usr/local/lib/python3.8/site-packages/scalex/function.py", line 127, in SCALEX
    outdir = outdir+'/'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by jsxlei** [comment]
Hi, we have fix the issue when turning off the results to disk. You can  reinstall the latest version by `pip install git+https://github.com/jsxlei/scalex.git`. The issue should be solved. Let me know if there is any problem. Thank you!
