### ISSUE TITLE
indices in VAE.encodeBatch

### ISSUE THREAD

**Issue by parashardhapola** [jsxlei/SCALEX#9]
Hi!

I'm reviewing the code and got confused by this line:

https://github.com/jsxlei/SCALEX/blob/531e3755da962853ecd2a622379addd37b290e3f/scalex/net/vae.py#L117

Why is `indices` being overwritten with zero values here?

**Comment by jsxlei** [comment]
I think this is a typo, though will not cause error if not return indices. Will fix it soon. Thank you for pointing out.

**Comment by parashardhapola** [comment]
I thought so too. Thanks for confirming.
